# Generated by Django 4.2.2 on 2023-12-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrary_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="register",
            name="email",
            field=models.EmailField(max_length=100),
        ),
    ]
