# Generated by Django 4.2.2 on 2023-12-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elibrary_app", "0002_alter_login_email_alter_register_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Login",
        ),
        migrations.DeleteModel(
            name="Register",
        ),
    ]
