# Generated by Django 4.2.2 on 2023-12-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elibrary_app", "0004_ebooksmodel_author_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ebooksmodel",
            name="author_id",
        ),
    ]
