# Generated by Django 4.2.2 on 2023-12-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrary_app", "0005_remove_ebooksmodel_author_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ebooksmodel",
            name="author",
            field=models.IntegerField(max_length=80),
        ),
    ]
