# Generated by Django 4.2.2 on 2023-12-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrary_app", "0007_remove_ebooksmodel_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="ebooksmodel",
            name="category",
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
