# Generated by Django 4.2.2 on 2023-12-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrary_app", "0008_ebooksmodel_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="ebooksmodel",
            name="author_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ebooksmodel",
            name="author",
            field=models.CharField(max_length=80),
        ),
    ]
